name: Hello Test
on:
  pull_request:
    types: [ opened, ready_for_review ]
jobs:
  hello-test:
    runs-on: ubuntu-latest
    name: Prints Hello World
    steps:
      - name: Do the actual printing
        runs: echo "Hello World!"